targets:
  $default:
    builders:
      gql_build|schema_builder:
        enabled: true
        options:
          schema: v1|lib/src/components/graphql/schema.graphql
          type_overrides:
            Upload:
              name: MultipartFile
              import: "package:http/http.dart"
      gql_build|ast_builder:
        enabled: true
      gql_build|data_builder:
        enabled: true
        options:
          schema: v1|lib/src/components/graphql/schema.graphql
          type_overrides:
            Upload:
              name: MultipartFile
              import: "package:http/http.dart"
      gql_build|var_builder:
        enabled: true
        options:
          schema: v1|lib/src/components/graphql/schema.graphql
          type_overrides:
            Upload:
              name: MultipartFile
              import: "package:http/http.dart"
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: v1|lib/src/components/graphql/schema.graphql
          custom_serializers:
            - import: "package:v1/src/components/graphql/serializers/upload_serializer.dart"
              name: UploadSerializer

      ferry_generator|req_builder:
        enabled: true
        options:
          schema: v1|lib/src/components/graphql/schema.graphql
          type_overrides:
            Upload:
              name: MultipartFile
              import: "package:http/http.dart"
